### ISSUE TITLE
npm run läuft aktuell als root

### ISSUE THREAD

**Issue by regnerisch** [labor-digital/docker-base-images#2]
https://github.com/labor-digital/docker-base-images/blob/a902103f90e5f1bd4a827d473497aeef9a05fa67/node12/node12/opt/bootstrap.sh#L23

@Neunerlei bitte mit @aweber-labor-digital besprechen

https://medium.com/better-programming/docker-for-node-js-in-production-b9dc0e9e48e0 siehe "2. Use a Nonroot Container User"

**Comment by toarni** [comment]
This is already solved via overwriting the npm command in the bash
